version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./samples.yaml:/app/samples.yaml
    environment:
      - ULTIPA_HOSTS=
      - ULTIPA_USERNAME=
      - ULTIPA_PASSWORD=
      - GRAPH_NAME=
      - SAMPLES_PATH=/app/samples.yaml
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
